### PR TITLE
Pass missing 'host' query parameter

### PR DESCRIPTION
**Pull request by kurakin-oleksandr**
One step closer for loading an app in admin.shopify.com

Should solve the issue https://github.com/gnikyt/laravel-shopify/issues/1248

### CODE REVIEW

**Comment by kurakin-oleksandr** [comment]
@Kyon147 can you please review my PR?

**Comment by Kyon147** [comment]
Hey @kurakin-oleksandr 

Can you explain what this is doing and how it fixes the issue in 1248 - just want to understand why passing the $host down to everything is the right approach.

**Comment by kurakin-oleksandr** [comment]
`host` might be not only "your-shop.shopify.com/admin" but also "admin.shopify.com/your-shop". The correct host is passed everywhere else except these places. Instead of constructing a host using `base64_encode($shop->getDomain()->toNative().'/admin')`, host should be accepted from the previous request and passed to the next one.
These changes are required to enable a new domain `admin.shopify.com/your-shop`

**Comment by Kyon147** [comment]
@kurakin-oleksandr thanks for explaining, will get this merged in.

**Comment by Shoaib-345** [comment]
@kurakin-oleksandr I solved the issue for "admin.shopify.com" but now I got a redirection issue to this URL **(/admin/admin/apps/API_KEY/api/authenticate/token)** while installing to the old domain "mystore.myshopify.com"
 after **/api/authenticate/token**. 
 Did you find any solution for this redirection where we got 2 times (/admin/admin)? and where this URL is made? If you have this issue resolved then please let me know or any reference would be highly appreciated.
 
 Thanks

**Comment by Kyon147** [comment]
Hey @kurakin-oleksandr 

I've spent some time this morning and going to incorporate this back into the next release. Seems like there was another issue on billing which falsely flagged this as an issue but it wasn't.

Thanks for your work on this PR, much appreicated.

**Comment by CodaemonHaroon** [comment]
Hi there,
I am not able to call the pages or pages are not loading. 
I am working on laravel/ossiset packge. I have a listing page which have internal links for the getRecord for Add/Update.
When Clicking on those lin the HOST is missed and not coming in the request.
I tried by passing in the url but no luck.
hope anyone help.

**Comment by Kyon147** [comment]
@CodaemonHaroon are you using the latest version of the package?

**Comment by Kyon147** [comment]
@CodaemonHaroon you are using the older version of the package, you should be using `kyon147/laravel-shopify`

**Comment by CodaemonHaroon** [comment]
@Kyon147 Thank you for your quick response. hope in latest package Session will also work which is vanishing while redirecting.

**Pull request merged**
