### PR TITLE
Feature/verify theme support

### PR DESCRIPTION
**Pull request by rvibit**
As mentioned in this issue https://github.com/Kyon147/laravel-shopify/issues/18 , I tried to recreate this PR https://github.com/gnikyt/laravel-shopify/pull/1198 in this repo. this is my first PR in any OSS so if there are any mistakes please guide me.

Note: need help with testing.

### CODE REVIEW

**Review by enmaboya — APPROVED** [review]

**Comment by Kyon147** [comment]
@enmaboya @rvibit - thanks for taking the time to move this into this package and for the review.

**Comment by Kyon147** [comment]
I'm going to pull this down locally and test it as well before merging it in, should be sometime next week.

**Comment by Kyon147** [comment]
@mohan-nishit the new tests have ran fine, so I'll have a look soon and get this into the package.

**Comment by mohan-nishit** [comment]
Thanks! Appreciate it!

**Comment by Kyon147** [comment]
@rvibit @mohan-nishit I've run this today on my local, and there is a problem with the installation using this branch. Master installs fine, but with this branch, there is a missing auth error that happens.

Can one of you take a look?

**Comment by Kyon147** [comment]
Nvm, found the issue - did not realise we added a migration. 

image

**Review by Kyon147 — APPROVED** [review]

**Pull request merged**
