### PR TITLE
Revert the recent changes as they are breaking the install.

### PR DESCRIPTION
**Pull request by Kyon147**

### CODE REVIEW

**Comment by Kyon147** [comment]
I've tested the billing and it works as expected.

Are you making sure you are passing the shop, like so?

` <p><a href="{{ route('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}">Upgrade</a></p>`

**Comment by rvibit** [comment]
> I've tested the billing and it works as expected.
> 
> Are you making sure you are passing the shop, like so?
> 
> ` <p><a href="{{ route('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}">Upgrade</a></p>`

Yes, I have already fixed that issue by passing the shop param manually.  I just wanted to know what other issues you are facing so you reverted the changes?

**Comment by Kyon147** [comment]
There were two recent PR's by another person which added the `host` down into the billing etc but it seemed to be causing some issues on new installs. 

To keep things clean, I reverted back to before those PRs were added in, and res-tested and the package is working as expected.

**Comment by rvibit** [comment]
> There were two recent PR's by another person which added the `host` down into the billing etc but it seemed it could be causing some issues on new installs.
> 
> To keep things clean, I reverted back to before those PRs were added in, and res-tested and the package is working as expected.

ok got it, thanks for the update.

**Comment by jackwefullfill** [comment]
hi @Kyon147, this means that #1 and #2 are not valid right? and we are still not able to load the app inside admin.shopify.com?

**Comment by Kyon147** [comment]
We need to remove the `shopOrigin` from the appBridge set up as the main concern. Then it just needs to be tested on an `admin.shopify` domain.

**Pull request merged**
