### PR TITLE
Replace legacy app bridge with app bridge cdn

### PR DESCRIPTION
**Pull request by enmaboya**
1. The code related to Turbolinks has been removed because Turbolinks has not been supported or maintained since 2021.
2. No separate support for Livewire has been added either, as the approach differs between Livewire 2 and Livewire 3. It might be better to add this information to the README later.

### CODE REVIEW

**Comment by Kyon147** [comment]
I've just seen you complete this just before I pushed up my update #362  so I am going to close mine in favour of yours and will review it shortly. 

Thanks @enmaboya

**Comment by Kyon147** [comment]
@VivekShingala the new release is going to be sometime later today 👍

**Comment by VivekShingala** [comment]
> @VivekShingala the new release is going to be sometime later today 👍

Thanks a lot @Kyon147

**Comment by jsalguero94** [comment]
Hi @Kyon147 @enmaboya , I just updated to the new version and I got this error when I tried to install the app in Shopify. This did not happen with the previous version. I'm using Blade and I have made a migrate:fresh and cleared the cache several times. thanks

image

**Comment by d-shannon** [comment]
Great work on this @enmaboya! Running smoothly for me.

**Comment by tariqbilal** [comment]
how can I make sure app bridge is loading perfectly fine. I am using the latest package but i am also using vuejs

**Pull request merged**
