### PR TITLE
Moved the API namespace from osiset to gnikyt

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
This is a fix with reference to the issue:  #166

### CODE REVIEW

**Comment by SachinBahukhandi** [comment]
@Kyon147 I fixed the linting and ran tests. Could you please review?

**Review by Kyon147 — APPROVED** [review]
This looks good.

TODO: add the upgrade instructions to the wiki as you wiki need to edit the config files too if you already have an installed app.

**Comment by SachinBahukhandi** [comment]
> This looks good.
> 
> TODO: add the upgrade instructions to the wiki as you wiki need to edit the config files too if you already have an installed app.

Shall that go on this PR or as a separate one?

**Comment by SachinBahukhandi** [comment]
@Kyon147 Ok I just came to know that we can update wiki directly, thus if it appears to be fine. Kindly merge the PR. Much thanks!

**Comment by Kyon147** [comment]
@SachinBahukhandi yeah sorry that Todo was more for me to remember!

**Pull request merged**
